{
 "title": "Goplot Chia Farmer",
 "description": "Sample dashboard for use with goplot; search github for goplot",
 "tags": [
  "goplot",
  "chia",
  "blockchain"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "remote_harvester1", "query": "harvester:9100" },
   { "name": "plotter1", "query": "localhost:9100" },
   { "name": "farmer1", "query": "localhost:9100" }
  ]
 },
 "panels": [
  { "title": "Farm Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Full Node Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "farm_fullnode_syncstatus{instance=\"$farmer1\"}"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_fullnode_difficulty{instance=\"$farmer1\"}"
    }
   ]
  },
  {
   "title": "Est Net Space",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_fullnode_netspace{instance=\"$farmer1\"}"
    }
   ]
  },
  {
   "title": "Eligible Plots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "farm_harvester_plots_eligible{instance=\"$remote_harvester1\"}",
     "legendFormat": "Harvester"
    },
    {
     "expr": "farm_harvester_plots_eligible{instance=\"$plotter1\"}",
     "legendFormat": "Plotter"
    }
   ]
  },
  {
   "title": "XCH Win Rates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "((sum (farm_plots_size) * .001) / sum (farm_fullnode_netspace))  * 4608 * 2",
     "legendFormat": "Estimated"
    },
    {
     "expr": "rate(farm_xch_farmed[1d]) * 86400",
     "legendFormat": "1 Day"
    },
    {
     "expr": "rate(farm_xch_farmed[3d]) * 86400",
     "legendFormat": "3 Day"
    },
    {
     "expr": "rate(farm_xch_farmed[7d]) * 86400",
     "legendFormat": "7 Day"
    }
   ]
  },
  {
   "title": "Farmer Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "farm_farmer_farmstatus{instance=\"$farmer1\"}"
    }
   ]
  },
  {
   "title": "Farm Plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(farm_plot_count)" }
   ]
  },
  {
   "title": "Farm Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(farm_plots_size)" }
   ]
  },
  {
   "title": "Harvester Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "farm_harvester_status{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "XCH",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(farm_xch_farmed)" }
   ]
  },
  {
   "title": "Est Win Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(farm_plots_size) * .001) / sum(farm_fullnode_netspace) * 4608 * 2"
    }
   ]
  },
  { "title": "Plotter Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "// Plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_running_plots{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "# Plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_plot_count{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$plotter1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$plotter1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$plotter1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Goplot Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_load5{instance=\"$plotter1\"}) + (node_load15{instance=\"$plotter1\"})) / 2"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "(node_load5{instance=\"$plotter1\"} + node_load15{instance=\"$plotter1\"}) / 2",
     "legendFormat": "avg_load"
    }
   ]
  },
  {
   "title": "Plots Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_plots_size{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "load_max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_loadmax{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$plotter1\"} * 100) / node_memory_MemTotal_bytes{instance=\"$plotter1\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$plotter1\"} - node_boot_time_seconds{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "plots/d",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(farm_plot_count{instance=\"$plotter1\"}[12h]) * 86400"
    }
   ]
  },
  {
   "title": "space/d",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(farm_plot_count{instance=\"$plotter1\"}[12h]) * 86400 * 101 *.001"
    }
   ]
  },
  {
   "title": "max_plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_maxplots{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "plot_gap",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_plot_gap{instance=\"$plotter1\"}"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$plotter1\"}"
    }
   ]
  },
  { "title": "Plotter Farm Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_merged_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read merged"
    },
    {
     "expr": "irate(node_disk_writes_merged_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Write merged"
    }
   ]
  },
  {
   "title": "Plotter Farm Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 13 },
   "repeat": "plotter1_farmdisks",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$plotter1\",mountpoint=~\"/farm/.*\"} * 100) / node_filesystem_size_bytes{instance=\"$plotter1\",mountpoint=~\"/farm/.*\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Remote Harvester Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "# Plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_plot_count{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "// Plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_running_plots{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "load_max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_loadmax{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$remote_harvester1\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$remote_harvester1\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$remote_harvester1\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Goplot Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_load5{instance=\"$remote_harvester1\"}) + (node_load15{instance=\"$remote_harvester1\"})) / 2"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(node_load5{instance=\"$remote_harvester1\"} + node_load15{instance=\"$remote_harvester1\"}) / 2",
     "legendFormat": "avg_load"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$remote_harvester1\"} * 100) / node_memory_MemTotal_bytes{instance=\"$remote_harvester1\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$remote_harvester1\"} - node_boot_time_seconds{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "Plots Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "farm_plots_size{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "max_plots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_maxplots{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  {
   "title": "plot_gap",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "goplot_config_plot_gap{instance=\"$remote_harvester1\"}"
    }
   ]
  },
  { "title": "Remote Harvester Farm Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Harvester Farm Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$remote_harvester1\",mountpoint=~\"/farm/.*\"} * 100) / node_filesystem_size_bytes{instance=\"$remote_harvester1\",mountpoint=~\"/farm/.*\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"$node\",job=\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Goplot Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "(node_load5{instance=\"$node\",job=\"$job\"} + node_load15{instance=\"$node\",job=\"$job\"}) / 2",
     "legendFormat": "avg_load"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - IO time"
    },
    {
     "expr": "irate(node_disk_discard_time_seconds_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - discard time"
    }
   ]
  },
  {
   "title": "Harvester Farm Disk Space Used",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$remote_harvester1\",device=~\"/dev/sd.1\"} - node_filesystem_avail_bytes{instance=\"$remote_harvester1\",device=~\"/dev/sd.1\"}) * .000000000001",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Plotter Farm Disk Space Used",
   "type": "graph",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$plotter1\",device=~\"/dev/sd.1\"} - node_filesystem_avail_bytes{instance=\"$plotter1\",device=~\"/dev/sd.1\"}) * .000000000001",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Hardware temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "celsius", "label": "temperature" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    },
    {
     "expr": "nvme_temperature_celsius{instance=\"$plotter1\",device=~\"nvme.n.\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}